### ISSUE TITLE
Comparing uri parameters as one String

### ISSUE THREAD

**Issue by Fizz55** [anyways-open/itinero-transit-server#15]
https://github.com/anyways-open/itinero-transit-server/blob/5ea4ab1e4c67f78468b135897bd3fcbd338c15cf/src/Itinero.Transit.Api/Logic/OtherModeBuilder.cs#L179

A uri encoded String containing the generator parameters is compared with a generated uri String to check if the used generator matches the requested parameters.
This works only when the parameters are always in the same order. For FirstLastMile this means the `default` profile needs to be passed first, then the `firstMile` and lastly the `lastMile`.
Not doing so results in an error code 500 and the following console log:
```
System.Exception: Something went very wrong here: the description does not match the generated value:
 expected:firstLastMile&firstMile=osm%26maxDistance%3D30000%26profile%3Debike&default=osm%26maxDistance%3D500%26profile%3Dpedestrian&lastMile=osm%26maxDistance%3D10000%26profile%3Dpedestrian
 Got: firstLastMile&default=osm&maxDistance=500&profile=pedestrian&firstMile=osm&maxDistance=30000&profile=ebike&lastMile=osm&maxDistance=10000&profile=pedestrian
```

**Comment by pietervdvn** [comment]
I've removed this check, although this needs some more work

**Comment by pietervdvn** [comment]
This system has changed completely
