### ISSUE TITLE
Routing issue - stations jump over eachother.

### ISSUE THREAD

**Issue by xivk** [anyways-open/itinero-transit-server#21]
https://routing.anyways.eu/transitapi/journey?from=https%3A%2F%2Fwww.openstreetmap.org%2F%23map%3D19%2F51.23243729627609%2F2.977133743796486&to=https%3A%2F%2Fwww.openstreetmap.org%2F%23map%3D19%2F51.14354341988667%2F4.800175474701518&departure=2019-09-05T09%3A47%3A00.000Z&inBetweenOsmProfile=crowsflight&inBetweenSearchDistance=0&firstMileOsmProfile=pedestrian&firstMileSearchDistance=5000&lastMileOsmProfile=pedestrian&lastMileSearchDistance=10000&multipleOptions=true => stations jump

![image](https://user-images.githubusercontent.com/1128068/64361327-3c340700-d004-11e9-9a21-82f2398f3718.png)

**Comment by pietervdvn** [comment]
Hypothesis: one connection is severely delayed. The next connection in the trip hasn't data added, resulting in weird journeys. To be tested

**Comment by pietervdvn** [comment]
https://routing.anyways.eu/transitapi/geojsonjourney?from=https%3A%2F%2Fwww.openstreetmap.org%2F%23map%3D19%2F51.1714445%2F4.144799&to=https%3A%2F%2Fwww.openstreetmap.org%2F%23map%3D19%2F51.036736000000005%2F3.711139&departure=2019-07-11T09%3A00%3A00.000Z

gives a weird order

{"type":"FeatureCollection","features":[{"geometry":{"type":"LineString","coordinates":[[4.144799,51.1714439],[4.1429615,51.1714745]]},"properties":{"stroke":"#2e3f57"},"type":"Feature"},{"geometry":{"type":"LineString","coordinates":[[4.1429615,51.1714745],[4.25951958,51.20834]]},"properties":{"stroke":"#5c514b"},"type":"Feature"},{"geometry":{"type":"LineString","coordinates":[[4.25951958,51.20834],[4.1429615,51.1714745],[4.088604,51.1509933],[3.98779035,51.1080666],[4.068938,51.1434],[3.8793807,51.08753],[3.74058723,51.056366],[3.756321,51.0386467],[3.71067,51.0359]]},"properties":{"stroke":"#8a623f"},"type":"Feature"},{"geometry":{"type":"LineString","coordinates":[[3.71067,51.0359],[3.711139,51.0367355]]},"properties":{"stroke":"#b87333"},"type":"Feature"}]}

**Comment by pietervdvn** [comment]
Root cause is confirmed. Tracking moved to https://github.com/openplannerteam/itinero-transit/issues/82
